// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef TouchScreen_horizontal_h
#define TouchScreen_horizontal_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "ts_head_file.h"
extern Fl_Double_Window *wd_touch_screen;
#include <FL/Fl_Wizard.H>
extern Fl_Wizard *wz_window_view;
#include <FL/Fl_Group.H>
extern Fl_Group *gp_main_file;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_setting;
extern Fl_Button *btn_main_file_back;
extern Fl_Group *gp_intercomm;
extern Fl_Button *btn_d2p_request_1;
extern Fl_Button *btn_d2p_request_2;
extern Fl_Button *btn_d2p_request_3;
extern Fl_Button *btn_d2p_request_4;
extern Fl_Button *btn_d2p_request_5;
extern Fl_Button *btn_d2p_request_6;
extern Fl_Button *btn_d2p_request_7;
extern Fl_Button *btn_d2p_request_8;
extern Fl_Button *btn_d2p_request_9;
extern Fl_Button *btn_d2p_request_10;
extern Fl_Button *btn_d2p_request_11;
extern Fl_Button *btn_d2p_request_12;
extern Fl_Button *btn_intercomm_accept;
extern Fl_Button *btn_intercomm_refuse;
extern Fl_Button *btn_intercomm_back;
extern Fl_Group *gp_static_show;
#include <FL/Fl_Tile.H>
extern Fl_Tile *title_static_volume_info;
extern Fl_Tile *title_tms_info_terminal_station;
#include <FL/Fl_Box.H>
#include <FL/Fl_Slider.H>
extern Fl_Slider *slider_d2d_intercomm_volume;
extern Fl_Tile *title_static_d2d_intercomm_volume;
extern Fl_Group *gp_input_password;
extern Fl_Button *btn_input_password_1;
extern Fl_Button *btn_input_password_2;
extern Fl_Button *btn_input_password_3;
extern Fl_Button *btn_input_password_4;
extern Fl_Button *btn_input_password_5;
extern Fl_Button *btn_input_password_6;
extern Fl_Button *btn_input_password_7;
extern Fl_Button *btn_input_password_8;
extern Fl_Button *btn_input_password_9;
extern Fl_Button *btn_input_password_cancle;
extern Fl_Button *btn_input_password_0;
extern Fl_Button *btn_input_password_ok;
extern Fl_Tile *title_please_input_password;
extern Fl_Tile *tile_out_password;
extern Fl_Tile *title_warning_and_forget_password;
extern Fl_Button *btn_forget_password;
extern Fl_Button *btn_input_password_back;
extern Fl_Group *gp_setting;
extern Fl_Tile *title_set_volume;
extern Fl_Button *btn_setting_back;
extern Fl_Button *btn_open_or_close_monitor;
extern Fl_Button *btn_setting_monitor_volume_sub;
extern Fl_Button *btn_setting_monitor_volume_inc;
extern Fl_Tile *title_setting_monitor_volume;
extern Fl_Tile *title_setting_car_volume;
extern Fl_Button *btn_setting_car_volume_sub;
extern Fl_Button *btn_setting_car_volume_inc;
extern Fl_Button *btn_setting_intercomm_volume_sub;
extern Fl_Button *btn_setting_intercomm_volume_inc;
extern Fl_Tile *title_setting_intercomm_volume;
extern Fl_Button *btn_setting_d2d_intercomm_volume_sub;
extern Fl_Tile *title_d2d_inercomm_volume;
extern Fl_Tile *title_setting_d2d_intercomm_volume;
extern Fl_Button *btn_setting_d2d_intercomm_volume_inc;
extern Fl_Group *gp_setting_items;
extern Fl_Button *btn_volume_adjust;
extern Fl_Button *btn_back_setting_items;
extern Fl_Tile *title_version_info;
extern Fl_Group *gp_window_black_screen;
extern Fl_Group *controlpage;
extern Fl_Button *pcu_1;
extern Fl_Button *pcu_2;
extern Fl_Button *pcu_3;
extern Fl_Button *pcu_4;
extern Fl_Button *pcu_5;
extern Fl_Button *pcu_6;
extern Fl_Button *pcu_7;
extern Fl_Button *pcu_8;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *btn_return;
extern Fl_Tile *title;
extern Fl_Button *enter_monitor;
extern Fl_Button *cancle_monitor;
extern Fl_Group *gp_select_car_ann_page;
extern Fl_Button *btn_ann_t1;
extern Fl_Button *btn_ann_t2;
extern Fl_Button *btn_ann_t3;
extern Fl_Button *btn_ann_t4;
extern Fl_Button *btn_ann_t5;
extern Fl_Button *btn_ann_t6;
extern Fl_Button *btn_ann_t7;
extern Fl_Button *btn_ann_t8;
extern Fl_Button *btn_ann_t9;
extern Fl_Button *btn_ann_t10;
extern Fl_Button *btn_ann_t11;
extern Fl_Button *next_page;
extern Fl_Return_Button *btn_return1;
extern Fl_Button *enter_select;
extern Fl_Button *cancel_select;
extern Fl_Group *AnnOrMonitorSelect;
extern Fl_Button *btn_enter;
extern Fl_Button *btn_monitor;
extern Fl_Tile *lable_state;
extern Fl_Return_Button *btn_return0;
extern Fl_Group *D2D_intercom_page;
extern Fl_Button *btn_d2d_1;
extern Fl_Button *btn_d2d_2;
extern Fl_Button *btn_d2d_3;
extern Fl_Button *btn_d2d_4;
extern Fl_Button *btn_d2d_5;
extern Fl_Button *btn_d2d_6;
extern Fl_Button *btn_d2d_7;
extern Fl_Button *btn_d2d_8;
extern Fl_Button *enter_d2d;
extern Fl_Return_Button *return_D2D;
extern Fl_Button *canenl_d2d;
extern Fl_Wizard *wz_select_window;
extern Fl_Group *main_group;
extern Fl_Button *btn_main_file;
extern Fl_Button *btn_emerg_ann;
extern Fl_Button *btn_live;
extern Fl_Button *btn_intercomm;
extern Fl_Group *gp_select_black;
int touch_screen_main();
void TouchScreenMain(int a, int b);
#endif
